---
anthill-cf-org:   "Demo"
anthill-cf-space: "demothymeleaf#prod"
anthill-cf-name:  "api.cf.lds.org"

applications:
  - name: "demothymeleaf"
    path: "../target/demothymeleaf.jar"
    buildpacks: ["java11"]
    instances: 2
    memory: "2G"
    env:
      SPRING_PROFILES_ACTIVE: "prod"
      TZ: "UTC"
    routes:
      - route: "demothymeleaf.app.lds.org/api/demothymeleaf"
    services:
      - "splunk"
